gpu504-37 pinned to port 8890

To connect to the compute node gpu504-37 on IBEX running your jupyter notebook server,
you need to run following two commands in a terminal

1. Command to create ssh tunnel from you workstation/laptop to cs-login:
ssh -L 8890:gpu504-37:8890 dahala@glogin.ibex.kaust.edu.sa

Copy the link provided below by jupyter-server and replace the NODENAME with localhost before pasting it in your browser on your workstation/laptop

[W 2023-01-13 19:30:17.434 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-01-13 19:30:17.434 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-01-13 19:30:17.434 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-01-13 19:30:17.434 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2023-01-13 19:30:17.438 LabApp] JupyterLab extension loaded from /home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/jupyterlab
[I 2023-01-13 19:30:17.438 LabApp] JupyterLab application directory is /home/dahala/miniconda3/envs/mlashok/share/jupyter/lab
[I 19:30:17.444 NotebookApp] The port 8890 is already in use, trying another port.
[I 19:30:17.444 NotebookApp] Serving notebooks from local directory: /home/dahala/extremevaluelandslides
[I 19:30:17.444 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 19:30:17.444 NotebookApp] http://gpu504-37:8891/?token=3dd0d8c8cbcb15ba4b43f2e210ce708593af161f10de9bf4
[I 19:30:17.444 NotebookApp]  or http://127.0.0.1:8891/?token=3dd0d8c8cbcb15ba4b43f2e210ce708593af161f10de9bf4
[I 19:30:17.444 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:30:17.456 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/dahala/.local/share/jupyter/runtime/nbserver-134143-open.html
    Or copy and paste one of these URLs:
        http://gpu504-37:8891/?token=3dd0d8c8cbcb15ba4b43f2e210ce708593af161f10de9bf4
     or http://127.0.0.1:8891/?token=3dd0d8c8cbcb15ba4b43f2e210ce708593af161f10de9bf4
[I 19:32:07.935 NotebookApp] Creating new notebook in 
[I 19:32:08.122 NotebookApp] Kernel started: 7d7942a2-e4c5-4384-84e2-8979062d4ee7, name: python3
[W 19:32:08.143 NotebookApp] delete /testrun-jvsc-c9bc49fe-865c-4aaa-90e0-a556d9b240d15277bd15-9903-4287-b425-a89421e2ec4c.ipynb
2023-01-13 19:40:11.312385: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-13 19:40:28.694948: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/dahala/miniconda3/envs/mlashok/lib/:/home/dahala/miniconda3/envs/mlashok/lib/
2023-01-13 19:40:28.696018: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/dahala/miniconda3/envs/mlashok/lib/:/home/dahala/miniconda3/envs/mlashok/lib/
2023-01-13 19:40:28.696032: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
[I 19:52:51.978 NotebookApp] Kernel restarted: 7d7942a2-e4c5-4384-84e2-8979062d4ee7
[I 19:52:51.983 NotebookApp] Starting buffering for 7d7942a2-e4c5-4384-84e2-8979062d4ee7:776f8b00-a477-411f-a945-d9cb105c93dc
[I 19:52:52.995 NotebookApp] Restoring connection for 7d7942a2-e4c5-4384-84e2-8979062d4ee7:776f8b00-a477-411f-a945-d9cb105c93dc
2023-01-13 19:52:55.651699: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-13 19:52:57.795506: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/dahala/miniconda3/envs/mlashok/lib/:/home/dahala/miniconda3/envs/mlashok/lib/
2023-01-13 19:52:57.795607: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/dahala/miniconda3/envs/mlashok/lib/:/home/dahala/miniconda3/envs/mlashok/lib/
2023-01-13 19:52:57.795617: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-13 19:54:34.024672: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-13 19:54:40.699843: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10402 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:1b:00.0, compute capability: 6.1
[I 19:56:12.051 NotebookApp] Kernel restarted: 7d7942a2-e4c5-4384-84e2-8979062d4ee7
[I 19:56:12.056 NotebookApp] Starting buffering for 7d7942a2-e4c5-4384-84e2-8979062d4ee7:776f8b00-a477-411f-a945-d9cb105c93dc
[I 19:56:12.067 NotebookApp] Restoring connection for 7d7942a2-e4c5-4384-84e2-8979062d4ee7:776f8b00-a477-411f-a945-d9cb105c93dc
2023-01-13 19:56:14.920552: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-13 19:56:17.579646: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/dahala/miniconda3/envs/mlashok/lib/:/home/dahala/miniconda3/envs/mlashok/lib/
2023-01-13 19:56:17.579801: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/dahala/miniconda3/envs/mlashok/lib/:/home/dahala/miniconda3/envs/mlashok/lib/
2023-01-13 19:56:17.579818: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-13 19:56:34.063817: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-13 19:56:34.803217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10402 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:1b:00.0, compute capability: 6.1
Exception in thread SystemMonitor:
Traceback (most recent call last):
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 118, in _start
    asset.start()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/cpu.py", line 166, in start
    self.metrics_monitor.start()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/interfaces.py", line 168, in start
    logger.info(f"Started {self._process.name}")
AttributeError: 'NoneType' object has no attribute 'name'
Exception in thread SystemMonitor:
Traceback (most recent call last):
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 118, in _start
    asset.start()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/cpu.py", line 166, in start
    self.metrics_monitor.start()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/interfaces.py", line 168, in start
    logger.info(f"Started {self._process.name}")
AttributeError: 'NoneType' object has no attribute 'name'
Exception in thread SystemMonitor:
Traceback (most recent call last):
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 118, in _start
    asset.start()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/cpu.py", line 166, in start
    self.metrics_monitor.start()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/interfaces.py", line 168, in start
    logger.info(f"Started {self._process.name}")
AttributeError: 'NoneType' object has no attribute 'name'
Exception in thread SystemMonitor:
Traceback (most recent call last):
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 118, in _start
    asset.start()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/cpu.py", line 166, in start
    self.metrics_monitor.start()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/interfaces.py", line 168, in start
    logger.info(f"Started {self._process.name}")
AttributeError: 'NoneType' object has no attribute 'name'
Exception in thread SystemMonitor:
Traceback (most recent call last):
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 118, in _start
    asset.start()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/disk.py", line 76, in start
    self.metrics_monitor.start()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/interfaces.py", line 168, in start
    logger.info(f"Started {self._process.name}")
AttributeError: 'NoneType' object has no attribute 'name'
Exception in thread SystemMonitor:
Traceback (most recent call last):
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 118, in _start
    asset.start()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/cpu.py", line 166, in start
    self.metrics_monitor.start()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/interfaces.py", line 168, in start
    logger.info(f"Started {self._process.name}")
AttributeError: 'NoneType' object has no attribute 'name'
Exception in thread SystemMonitor:
Traceback (most recent call last):
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 118, in _start
    asset.start()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/disk.py", line 76, in start
    self.metrics_monitor.start()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/interfaces.py", line 168, in start
    logger.info(f"Started {self._process.name}")
AttributeError: 'NoneType' object has no attribute 'name'
Exception in thread SockSrvRdThr:
Traceback (most recent call last):
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/service/server_sock.py", line 112, in run
    shandler(sreq)
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/service/server_sock.py", line 174, in server_record_publish
    iface = self._mux.get_stream(stream_id).interface
  File "/home/dahala/miniconda3/envs/mlashok/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 206, in get_stream
    stream = self._streams[stream_id]
KeyError: 'd0p5htvu'
[I 20:22:16.402 NotebookApp] Kernel restarted: 7d7942a2-e4c5-4384-84e2-8979062d4ee7
[I 20:22:16.407 NotebookApp] Starting buffering for 7d7942a2-e4c5-4384-84e2-8979062d4ee7:776f8b00-a477-411f-a945-d9cb105c93dc
[I 20:22:16.418 NotebookApp] Restoring connection for 7d7942a2-e4c5-4384-84e2-8979062d4ee7:776f8b00-a477-411f-a945-d9cb105c93dc
2023-01-13 20:22:34.094666: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-13 20:22:37.722049: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/dahala/miniconda3/envs/mlashok/lib/:/home/dahala/miniconda3/envs/mlashok/lib/
2023-01-13 20:22:37.723026: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/dahala/miniconda3/envs/mlashok/lib/:/home/dahala/miniconda3/envs/mlashok/lib/
2023-01-13 20:22:37.723041: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
