2023-01-18 15:18:03,812 INFO    MainThread:122621 [wandb_setup.py:_flush():68] Configure stats pid to 122621
2023-01-18 15:18:03,812 INFO    MainThread:122621 [wandb_setup.py:_flush():68] Loading settings from /home/dahala/.config/wandb/settings
2023-01-18 15:18:03,812 INFO    MainThread:122621 [wandb_setup.py:_flush():68] Loading settings from /home/dahala/extremevaluelandslides/wandb/settings
2023-01-18 15:18:03,812 INFO    MainThread:122621 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-18 15:18:03,812 INFO    MainThread:122621 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-01-18 15:18:03,812 INFO    MainThread:122621 [wandb_init.py:_log_setup():476] Logging user logs to /home/dahala/extremevaluelandslides/wandb/run-20230118_151803-w2mao8h5/logs/debug.log
2023-01-18 15:18:03,812 INFO    MainThread:122621 [wandb_init.py:_log_setup():477] Logging internal logs to /home/dahala/extremevaluelandslides/wandb/run-20230118_151803-w2mao8h5/logs/debug-internal.log
2023-01-18 15:18:03,812 INFO    MainThread:122621 [wandb_init.py:init():516] calling init triggers
2023-01-18 15:18:03,812 INFO    MainThread:122621 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {'bs': 12}
2023-01-18 15:18:03,812 INFO    MainThread:122621 [wandb_init.py:init():535] re-initializing run, found existing run on stack: 371i7ujb
2023-01-18 15:18:03,816 INFO    MainThread:122621 [wandb_run.py:_finish():1753] finishing run dahal/Extreme Value/371i7ujb
2023-01-18 15:18:03,816 INFO    MainThread:122621 [jupyter.py:save_history():448] not saving jupyter history
2023-01-18 15:18:03,816 INFO    MainThread:122621 [jupyter.py:save_ipynb():378] not saving jupyter notebook
2023-01-18 15:18:03,816 INFO    MainThread:122621 [wandb_init.py:_jupyter_teardown():408] cleaning up jupyter logic
2023-01-18 15:18:03,816 INFO    MainThread:122621 [wandb_run.py:_atexit_cleanup():1955] got exitcode: 0
2023-01-18 15:18:03,817 INFO    MainThread:122621 [wandb_run.py:_restore():1938] restore
2023-01-18 15:18:03,817 INFO    MainThread:122621 [wandb_run.py:_restore():1944] restore done
2023-01-18 15:18:11,585 INFO    MainThread:122621 [wandb_run.py:_footer_history_summary_info():3408] rendering history
2023-01-18 15:18:11,586 INFO    MainThread:122621 [wandb_run.py:_footer_history_summary_info():3440] rendering summary
2023-01-18 15:18:11,602 INFO    MainThread:122621 [wandb_run.py:_footer_sync_info():3364] logging synced files
2023-01-18 15:18:11,618 INFO    MainThread:122621 [wandb_init.py:init():569] starting backend
2023-01-18 15:18:11,618 INFO    MainThread:122621 [wandb_init.py:init():573] setting up manager
2023-01-18 15:18:11,621 INFO    MainThread:122621 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-01-18 15:18:11,622 INFO    MainThread:122621 [wandb_init.py:init():580] backend started and connected
2023-01-18 15:18:11,643 INFO    MainThread:122621 [wandb_run.py:_label_probe_notebook():1116] probe notebook
2023-01-18 15:18:11,643 INFO    MainThread:122621 [wandb_run.py:_label_probe_notebook():1126] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-01-18 15:18:11,643 INFO    MainThread:122621 [wandb_init.py:init():658] updated telemetry
2023-01-18 15:18:11,854 INFO    MainThread:122621 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2023-01-18 15:18:12,742 WARNING MainThread:122621 [wandb_init.py:init():1099] interrupted
Traceback (most recent call last):
  File "/home/dahala/miniconda3/envs/dlashok/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/dahala/miniconda3/envs/dlashok/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 697, in init
    result = handle.wait(
  File "/home/dahala/miniconda3/envs/dlashok/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 261, in wait
    found = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/dahala/miniconda3/envs/dlashok/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 118, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/dahala/miniconda3/envs/dlashok/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 114, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/dahala/miniconda3/envs/dlashok/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/home/dahala/miniconda3/envs/dlashok/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-01-18 15:18:13,038 INFO    MainThread:122621 [wandb_init.py:_resume_backend():398] resuming backend
